# Generated by Django 4.1.7 on 2023-03-29 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='bus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule_bus', models.CharField(max_length=12)),
                ('nb_place', models.PositiveSmallIntegerField(default=0)),
                ('compagnie_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.compagnie')),
            ],
        ),
        migrations.CreateModel(
            name='date_depart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ladate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle_grd', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='heure_depart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('l_heure', models.TimeField(default='05:00.0')),
            ],
        ),
        migrations.CreateModel(
            name='ville',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_ville', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='v_depart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ville_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='companyman.ville')),
            ],
        ),
        migrations.CreateModel(
            name='v_arrivee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ville_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='companyman.ville')),
            ],
        ),
        migrations.CreateModel(
            name='utilisateur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_user', models.CharField(max_length=30)),
                ('prenom_user', models.CharField(max_length=50)),
                ('email_user', models.CharField(max_length=60)),
                ('id_user', models.CharField(max_length=10)),
                ('pw_user', models.CharField(max_length=12)),
                ('compagnie_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.compagnie')),
                ('grade_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='companyman.grade')),
            ],
        ),
        migrations.CreateModel(
            name='ligne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix', models.FloatField(default=0)),
                ('ville_arr', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='companyman.v_arrivee')),
                ('ville_dep', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='companyman.v_depart')),
            ],
        ),
        migrations.CreateModel(
            name='infoligne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='companyman.bus')),
                ('date_dep', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='companyman.date_depart')),
                ('heure_dep', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='companyman.heure_depart')),
                ('ligne_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='companyman.ligne')),
            ],
        ),
    ]
