# Generated by Django 4.1.7 on 2023-03-29 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        ('akst', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='date_depart',
            name='infoln_id',
        ),
        migrations.RemoveField(
            model_name='infoligne',
            name='bus_id',
        ),
        migrations.RemoveField(
            model_name='infoligne',
            name='date_dep',
        ),
        migrations.RemoveField(
            model_name='infoligne',
            name='heure_dep',
        ),
        migrations.RemoveField(
            model_name='infoligne',
            name='ligne_id',
        ),
        migrations.RemoveField(
            model_name='ligne',
            name='ville_arr',
        ),
        migrations.RemoveField(
            model_name='ligne',
            name='ville_dep',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='compagnie_id',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='grade_id',
        ),
        migrations.RemoveField(
            model_name='v_arrivee',
            name='ville_id',
        ),
        migrations.RemoveField(
            model_name='v_depart',
            name='ville_id',
        ),
        migrations.RemoveField(
            model_name='billet',
            name='reservation_id',
        ),
        migrations.AddField(
            model_name='billet',
            name='place',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='billet',
            name='compagnie_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.compagnie'),
        ),
        migrations.DeleteModel(
            name='bus',
        ),
        migrations.DeleteModel(
            name='compagnie',
        ),
        migrations.DeleteModel(
            name='date_depart',
        ),
        migrations.DeleteModel(
            name='grade',
        ),
        migrations.DeleteModel(
            name='heure_depart',
        ),
        migrations.DeleteModel(
            name='infoligne',
        ),
        migrations.DeleteModel(
            name='ligne',
        ),
        migrations.DeleteModel(
            name='reservation',
        ),
        migrations.DeleteModel(
            name='utilisateur',
        ),
        migrations.DeleteModel(
            name='v_arrivee',
        ),
        migrations.DeleteModel(
            name='v_depart',
        ),
        migrations.DeleteModel(
            name='ville',
        ),
    ]
