# Generated by Django 3.1.2 on 2023-03-11 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('akst', '0003_date_depart_infoln_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='date_depart',
            name='infoln_id',
        ),
    ]
